import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReactQueryProvider from "@/providers/tan-stack-react-query-provider";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/navbar";
import { Montserrat } from "next/font/google";
import { cn } from "@/lib/utils";
import { SessionProvider } from "next-auth/react";
import Footer from "@/components/footer";

const montserrat = Montserrat({
  subsets: ["latin"],
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Scrimba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={`${cn(montserrat.className)} antialiased`}>
          <ReactQueryProvider>
            <Navbar />
            {children}
            <Footer/>
          </ReactQueryProvider>
          <Toaster />
        </body>
      </SessionProvider>
    </html>
  );
}
